### ISSUE TITLE
Consul support?

### ISSUE THREAD

**Issue by kelvinji2009** [wanghongfei/gogate#1]
Great job!
Do you have a plan to support  `Consul`?

**Comment by wanghongfei** [comment]
现在gogate的主要问题在于eureka client, 因为官方没有go client, 只有用第三方的，但是eureka的很多HTTP接口是在官网wiki里没写的，所以client功能也不够全;
比如拉取注册信息，目前实现是一次把所有的都拉下来，但是java的client是可以增量拉取的;

加consul其实没啥问题。。只是consul在国内用的其实挺少的

**Comment by kelvinji2009** [comment]
是啊， 只是长远来看，虽然Eureka暂时没有进入维护模式，以后说不定啊，所以我在考虑用consul作为第一候选。

**Comment by wanghongfei** [comment]
好，下一步就加consul，consul也是go写的，应该有全面的go client, 实现起来会比eureka好一些

**Comment by wanghongfei** [comment]
其实虽然eureka现在不开发了，但是对于绝大多数公司来说，eureka完全够用了。。实在不行还可以拉代码改改，就是个servlet就用，也没那么复杂

**Comment by kelvinji2009** [comment]
是的啊，小公司就是要避免瞎折腾。不过可以实现多注册中心，爱注册到哪就注册到哪。

**Comment by wanghongfei** [comment]
干，加consul

**Comment by kelvinji2009** [comment]
这效率，哈哈！666

**Comment by cqyisbug** [comment]
我被作者逗笑了。说着说着就加了。

**Comment by ooocici** [comment]
幽默的作者，好想抱抱你。
